### PR TITLE
Folder structure and namespaces

### PR DESCRIPTION
**Pull request by hybridherbst**
Proposal for clearer separation between topics.
Two things bug me a bit:
- naming of "RegistryManager" (should be RegistryManagerView) and RegistryManagerController (should be RegistryManager)
- dependency of NPM (in Core) on PublishingManifest (in Publishing) - could be resolved by having a partial class with the publishing parts of NPM only being there

### CODE REVIEW

**Comment by jespersmith** [comment]
I like it.

- RegistryManager should be RegistryManagerView. I would keep the name RegistryManagerController (I tried to make a Model–view–controller architecture, however I'm not a GUI programmer)
- PublishingManifest is very much NPM specific. I propose moving it to NPM and rename it to NPMPublishingManifest

**Comment by jespersmith** [comment]
Just to clarify: PublicationManifest is the JSON data that gets send to the NPM server to store the package.

**Comment by hybridherbst** [comment]
I'd not keep "Controller" appended to match the others (CredentialManager also does not have Controller).

Also makes the "Core" folder read nice: when working with scoped registries, you now have a core of "CredentialManager", "RegistryManager", "ScopedRegistry" and "NPM" which feels ok.

Also after taking another look I think PublishingManifest should stay where it is for now; it has a dependency on PackageTarball anyways (so this is mangled one way or the other).

For the future I think it makes sense to de-tangle Core and Publishing more but for now I think it's fine.

**Comment by jespersmith** [comment]
Thank you very much for this commit. Refactoring for easier maintenance is always good.

I renamed Publishing to NPM and split NPM.cs in NPMPublish.cs and NPMLogin.cs and moved them in the NPM namespace. I think NPM is a better name than Publishing, as it is very specific to the npm protocol.

**Pull request merged**
